### ISSUE TITLE
About the annotation files of AI-TOD

### ISSUE THREAD

**Issue by haotianll** [jwwangchn/AI-TOD#15]
Hi,

I follow the orignal instruction and aitodtoolkit and I get some annotation files, but I find the numbers of instances are not consistent as reported in AI-TOD paper. So I want to know if there are any processed annotation files that can be used directly.

I listed the results as following:
![image](https://user-images.githubusercontent.com/26497931/188127971-9463313b-5141-4088-b1d9-012ac0128230.png)

My results:
<html>

category_id | aitod_train.json | aitod_val.json | aitod_trainval.json | aitod_test.json
-- | -- | -- | -- | --
1 | 623 | 170 | 793 | 745
2 | 512 | 140 | 652 | 689
3 | 5269 | 2477 | 7746 | 5860
4 | 13539 | 3791 | 17330 | 17633
5 | 293 | 34 | 327 | 292
6 | 248051 | 59906 | 307957 | 306678
7 | 14126 | 3841 | 17967 | 15443
8 | 176 | 67 | 243 | 290
total | 282589 | 70426 | 353015 | 347630
</body>
</html>

**Comment by Chasel-Tsui** [comment]
> Hi,
> 
> I follow the orignal instruction and aitodtoolkit and I get some annotation files, but I find the numbers of instances are not consistent as reported in AI-TOD paper. So I want to know if there are any processed annotation files that can be used directly.
> 
> I listed the results as following: ![image](https://user-images.githubusercontent.com/26497931/188127971-9463313b-5141-4088-b1d9-012ac0128230.png)
> 
> My results:
> 
> category_id	aitod_train.json	aitod_val.json	aitod_trainval.json	aitod_test.json
> 1	623	170	793	745
> 2	512	140	652	689
> 3	5269	2477	7746	5860
> 4	13539	3791	17330	17633
> 5	293	34	327	292
> 6	248051	59906	307957	306678
> 7	14126	3841	17967	15443
> 8	176	67	243	290
> total	282589	70426	353015	347630

Hi, Thanks for pointing it out. I have checked it. The difference may result from the fact that we have provided two versions of AI-TOD in this repo, the statistical information of the first version (the whole AI-TOD was publicly available before 2022/06) is the same as that in the paper. While due to a license conflict with xView, we then disable the public download link of AI-TOD, you may need to generate the AI-TOD from the provided code, obtaining the second version of AI-TOD, your provided result is the statistical information of the second version. The difference may result from the difference in the code of dataset generation. 
We have also checked that the instances in the two versions only differ marginally which will not have an obvious impact on the final detection performance. If you want to download the previous public version, please provide an e-mail address.

**Comment by haotianll** [comment]
Thank you so much for your reply!
My email address is haotianliu001@hotmail.com .
